import os
from ase.io import read, write
from ase.io.proteindatabank import write_proteindatabank


def write_xyz_file(filename, atoms, mode='a', sig=16, header="Generated by torsionfit"):
    """
    Write one XYZ frame with 'general' float formatting (like tool.py):
    - sig: significant digits (e.g., 16)
    - switches automatically between fixed and scientific notation.
    """
    import os
    os.makedirs(os.path.dirname(filename) or ".", exist_ok=True)

    fmt = f".{sig}g"  
    lines = []
    lines.append(f"{len(atoms)}\n")
    lines.append(f"{header}\n")
    for atom in atoms:
        x, y, z = atom.position
        lines.append(
            f"{atom.symbol} {format(x, fmt)} {format(y, fmt)} {format(z, fmt)}\n"
        )
    with open(filename, mode, encoding="utf-8") as f:
        f.writelines(lines)


def read_atoms(path):
    return read(path)

def write_pdb(path, atoms):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    write_proteindatabank(path, atoms)
