"""
I/O and orchestration helpers for anti_torsionator.

Responsibilities:
  - Basic file I/O (PDB, XYZ)
  - Argument validation
  - Path helpers for the scanning directory tree
  - Wrappers that drive GAFF2 old/new refinement and parametrization
  - Cumulative frcmod bookkeeping
"""

import glob as _glob
import os
import shutil
import subprocess
from typing import Dict, List, Optional, Tuple

import numpy as np
from ase.io.proteindatabank import write_proteindatabank
from rdkit import Chem

from .paramfit.cpptraj import write_xyz_to_nc_in
from .paramfit.amber_refinement import (
    Gaff2NewDihedralRefinement,
    Gaff2SingleDihedralRefinement,
    find_best_hrst_by_RMSE,
    get_atom_types_from_mol2,
    param_input_file,
    read_basis_from_frcmod,
    update_frcmod,
)


# ============================================================================
# Shared helpers
# ============================================================================

def _int_stem_key(path: str) -> int:
    """Sort key: extract integer stem from a PDB filename (e.g. '3.pdb' → 3)."""
    return int(os.path.basename(path).split(".")[0])


# ============================================================================
# Basic I/O
# ============================================================================

def write_xyz_file(
    filename: str,
    atoms,
    mode: str = "a",
    sig: int = 16,
    header: str = "Generated by torsionator",
) -> None:
    os.makedirs(os.path.dirname(filename) or ".", exist_ok=True)
    fmt = f".{sig}g"
    lines = [f"{len(atoms)}\n", f"{header}\n"]
    for atom in atoms:
        x, y, z = atom.position
        lines.append(f"{atom.symbol} {format(x, fmt)} {format(y, fmt)} {format(z, fmt)}\n")
    with open(filename, mode, encoding="utf-8") as f:
        f.writelines(lines)


def write_pdb(path: str, atoms) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    write_proteindatabank(path, atoms)


# ============================================================================
# Logging helpers
# ============================================================================

def banner(log, title: str, char: str = "=") -> None:
    line = char * max(60, len(title) + 10)
    log.info("%s", line)
    log.info("  %s", title)
    log.info("%s", line)


# ============================================================================
# Backup helpers (PLUMED-style bck.X.<name>)
# ============================================================================

_OUTPUT_NAMES = ["scanning", "conformers", "parameters", "workflow.log"]


def backup_existing_outputs(base_dir: str) -> Optional[int]:
    """Rename pre-existing torsionator output dirs/files to bck.X.<name>.

    Follows the PLUMED convention: bck.0.<name>, bck.1.<name>, …
    All items from the same previous run get the same index X, chosen as
    the lowest integer for which no bck.X.* entry already exists in base_dir.
    Returns the backup index used, or None if nothing needed backing up.
    """
    # Collect items that exist
    items: List[str] = []
    for name in _OUTPUT_NAMES:
        if os.path.exists(os.path.join(base_dir, name)):
            items.append(name)
    for path in _glob.glob(os.path.join(base_dir, "minimized_*.pdb")):
        items.append(os.path.basename(path))

    if not items:
        return None

    # Find the lowest unused backup index
    used: set = set()
    if os.path.isdir(base_dir):
        for entry in os.listdir(base_dir):
            parts = entry.split(".")
            if len(parts) >= 3 and parts[0] == "bck":
                try:
                    used.add(int(parts[1]))
                except ValueError:
                    pass

    idx = 0
    while idx in used:
        idx += 1

    for name in items:
        src = os.path.join(base_dir, name)
        dst = os.path.join(base_dir, f"bck.{idx}.{name}")
        os.rename(src, dst)
        print(f"Backup: {name} -> bck.{idx}.{name}")

    return idx


# ============================================================================
# Argument validation
# ============================================================================

def norm_flag(x: Optional[str]) -> Optional[str]:
    if x is None:
        return None
    s = str(x).strip().lower()
    return None if s in ("none", "", "null") else s


def validate_step_size(step_size: int) -> int:
    try:
        step = int(step_size)
    except Exception as exc:
        raise ValueError(f"step_size must be int-like, got {step_size!r}") from exc
    if step <= 0:
        raise ValueError(f"step_size must be > 0, got {step}")
    if 360 % step != 0:
        raise ValueError(f"step_size must divide 360 exactly, got {step}")
    return step


def validate_user_dihedral_indices(pdb_file: str, d_tup: Tuple[int, int, int, int]) -> None:
    """Validate that (a, b, c, d) form a bonded dihedral in the PDB (0-based indices)."""
    mol = Chem.MolFromPDBFile(pdb_file, removeHs=False)
    if mol is None:
        raise ValueError(f"RDKit could not read PDB: {pdb_file}")

    n = mol.GetNumAtoms()
    for idx in d_tup:
        if not (0 <= idx < n):
            raise ValueError(f"Atom index {idx} out of range [0, {n - 1}]")

    a, b, c, d = d_tup

    def bonded(i, j):
        return mol.GetBondBetweenAtoms(int(i), int(j)) is not None

    if not (bonded(a, b) and bonded(b, c) and bonded(c, d)):
        raise ValueError(
            f"Indices {list(d_tup)} do not define a bonded dihedral "
            "(required bonds: a-b, b-c, c-d)."
        )


# ============================================================================
# Path helpers
# ============================================================================

def _dstr(d_tup: Tuple[int, int, int, int]) -> str:
    return "_".join(map(str, d_tup))


def _scan_root(cfg, d_tup: Tuple[int, int, int, int]) -> str:
    return os.path.join(cfg.base_dir, "scanning", _dstr(d_tup))


def _method_dir(cfg, d_tup: Tuple[int, int, int, int], method: str, MCS: bool) -> str:
    root = _scan_root(cfg, d_tup)
    sub = os.path.join(method, "MCS") if MCS else method
    return os.path.join(root, sub)


def _method_subdir(cfg, d_tup: Tuple[int, int, int, int], method: str, MCS: bool) -> str:
    return os.path.relpath(_method_dir(cfg, d_tup, method, MCS), _scan_root(cfg, d_tup))


def _nn_energy_file(cfg, d_tup: Tuple[int, int, int, int], method: str, MCS: bool) -> str:
    return os.path.join(_method_dir(cfg, d_tup, method, MCS), "angles_vs_energies_final.txt")


def _gaff2_old_dir(cfg, d_tup: Tuple[int, int, int, int], method: str) -> str:
    return os.path.join(_scan_root(cfg, d_tup), "GAFF2", "old", method)


def _gaff2_new_dir(cfg, d_tup: Tuple[int, int, int, int], method: str) -> str:
    return os.path.join(_scan_root(cfg, d_tup), "GAFF2", "new", method)


def _gaff2_old_ante_dir(cfg, d_tup: Tuple[int, int, int, int], method: str) -> str:
    return os.path.join(_gaff2_old_dir(cfg, d_tup, method), "antechamber")


# ============================================================================
# Minimization
# ============================================================================

def minimize_input(cfg, opt, calc_factory, log, pdb_file: str, methods: List[str]) -> Dict[str, str]:
    out: Dict[str, str] = {}
    for m in methods:
        log.info("→ Minimizing input with %s", m)
        calc, label = calc_factory.get(m)
        out_path = os.path.join(cfg.base_dir, f"minimized_{label}.pdb")
        opt.minimize_and_write_pdb(pdb_file, calc, out_path)
        out[m] = out_path
    return out


# ============================================================================
# NN scan wrapper
# ============================================================================

def run_nn_scan(
    log,
    scanner,
    pdb_for_scan: str,
    calc,
    d_tup: Tuple[int, int, int, int],
    label: str,
    method: str,
    step_size: int = 10,
) -> None:
    step_size = validate_step_size(step_size)
    log.info("[NN][%s][%s] scan (label=%s, step_size=%s)", method, d_tup, label, step_size)
    scanner.scan(pdb_for_scan, calc, d_tup, label, step_size=step_size)


# ============================================================================
# GAFF2 wrappers
# ============================================================================

def detect_basis_from_antechamber(
    log,
    cfg,
    d_tup: Tuple[int, int, int, int],
    method: str,
) -> Tuple[int, ...]:
    """Read the periodicity terms from the GAFF2/old antechamber frcmod for
    *d_tup* and return them as a basis tuple (same sign convention as
    ``_basis_from_max_mult``).  Call this after ``run_gaff2_old`` has finished.
    """
    ante_dir = _gaff2_old_ante_dir(cfg, d_tup, method)
    frcmod_path = os.path.join(ante_dir, "MOL.frcmod")
    mol2_path = os.path.join(ante_dir, "MOL.mol2")
    basis = read_basis_from_frcmod(frcmod_path, mol2_path, d_tup, log=log)
    log.info("[AUTO-BASIS][%s][%s] detected basis from antechamber frcmod: %s", method, d_tup, basis)
    return basis


def run_gaff2_old(
    log,
    cfg,
    ROOT: str,
    method: str,
    d_tup: Tuple[int, int, int, int],
    pdb_for_scan: str,
    basis_periodicities: Optional[Tuple[int, ...]] = None,
    postscan_make_expanded_for_mdgx: bool = True,
    MCS: bool = False,
    mcs_xyz: Optional[str] = None,
    step_size: int = 10,
    net_charge: int = 0,
    spin: int = 1,
) -> None:
    if basis_periodicities is None:
        basis_periodicities = (-6, -4, -3, -2, 1)

    step_size = validate_step_size(step_size)
    log.info("[GAFF2/old][%s][%s] refinement (MCS=%s, step_size=%s)", method, d_tup, MCS, step_size)

    ref = Gaff2SingleDihedralRefinement(cfg=cfg, log=log)
    ref.refine_old(
        root=ROOT,
        method=method,
        d_tup=d_tup,
        basis_periodicities=tuple(int(x) for x in basis_periodicities),
        input_pdb=pdb_for_scan,
        net_charge=net_charge,
        spin=spin,
        MCS=MCS,
        mcs_xyz=mcs_xyz,
        postscan_make_expanded_for_mdgx=postscan_make_expanded_for_mdgx,
        step_size=step_size,
    )


def run_gaff2_new(
    log,
    cfg,
    ROOT: str,
    method: str,
    d_tup: Tuple[int, int, int, int],
    pdb_for_scan: str,
    param_results: Dict[float, Dict[str, str]],
    MCS: bool = False,
    mcs_xyz: Optional[str] = None,
    step_size: int = 10,
    net_charge: int = 0,
    spin: int = 1,
) -> None:
    step_size = validate_step_size(step_size)
    log.info("[GAFF2/new][%s][%s] refinement (MCS=%s, step_size=%s)", method, d_tup, MCS, step_size)

    ref = Gaff2NewDihedralRefinement(cfg=cfg, log=log)
    ref.refine_new(
        root=ROOT,
        method=method,
        d_tup=d_tup,
        input_pdb=pdb_for_scan,
        param_results=param_results,
        MCS=MCS,
        mcs_xyz=mcs_xyz,
        step_size=step_size,
        net_charge=net_charge,
        spin=spin,
    )


# ============================================================================
# Expanded inputs (one-time postscan setup for mdgx)
# ============================================================================

def _ensure_expanded_inputs(
    cfg,
    log,
    method: str,
    d_tup: Tuple[int, int, int, int],
    basis_periodicities: Tuple[int, ...],
    expanded_tag: str = "expanded",
    tleap_cmd: str = "tleap",
) -> Tuple[str, str]:
    scan_root = _scan_root(cfg, d_tup)
    gaff2_old_method = os.path.join(scan_root, "GAFF2", "old", method)

    ante_exp = os.path.join(gaff2_old_method, f"antechamber_{expanded_tag}")
    leap_exp = os.path.join(gaff2_old_method, f"leap_{expanded_tag}")
    top_exp = os.path.join(leap_exp, "MOL.top")
    frcmod_exp = os.path.join(ante_exp, "MOL.frcmod")

    if os.path.isfile(top_exp) and os.path.isfile(frcmod_exp):
        log.info("[EXPANDED][%s][%s] reusing existing expanded inputs", method, d_tup)
        return top_exp, frcmod_exp

    ref = Gaff2SingleDihedralRefinement(cfg=cfg, log=log, tleap_cmd=tleap_cmd)
    return ref.postscan_expand_old_and_releap(
        method=method,
        d_tup=d_tup,
        basis_periodicities=tuple(int(x) for x in basis_periodicities),
        expanded_tag=expanded_tag,
    )


# ============================================================================
# cpptraj: XYZ → NC
# ============================================================================

def _ensure_nc_from_xyz(
    cfg,
    log,
    method: str,
    d_tup: Tuple[int, int, int, int],
    MCS: bool,
    use_old_expanded: bool,
) -> str:
    method_dir = _method_dir(cfg, d_tup, method, MCS)
    method_subdir = _method_subdir(cfg, d_tup, method, MCS)
    scan_dir = _scan_root(cfg, d_tup)

    leap_subdir = (
        f"GAFF2/old/{method}/leap_expanded"
        if use_old_expanded
        else f"GAFF2/old/{method}/leap"
    )

    xyz_path = os.path.join(method_dir, "geometries.xyz")
    nc_path = os.path.join(method_dir, "geometries.nc")

    if not os.path.isfile(xyz_path):
        raise FileNotFoundError(f"Missing geometries.xyz at {xyz_path}")

    write_xyz_to_nc_in(scan_dir, leap_subdir, method_subdir)

    inp_path = os.path.join(method_dir, "xyz_to_nc.in")
    if not os.path.isfile(inp_path):
        raise FileNotFoundError(f"cpptraj input not created: {inp_path}")

    log.info("[CPPTRAJ][%s][%s] xyz -> nc", method, d_tup)
    subprocess.run(
        ["cpptraj", "-i", "xyz_to_nc.in"],
        cwd=method_dir,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    if not os.path.isfile(nc_path):
        raise FileNotFoundError(f"cpptraj did not produce geometries.nc at {nc_path}")

    return nc_path


# ============================================================================
# Parametrization core
# ============================================================================

def parameterize_one_dihedral(
    cfg,
    log,
    m: str,
    d_tup: Tuple[int, int, int, int],
    MCS: bool = False,
    hrst_values: Optional[List[float]] = None,
    basis_periodicities: Optional[Tuple[int, ...]] = None,
    expand_basis: bool = True,
) -> Dict[float, Dict[str, str]]:
    if basis_periodicities is None:
        basis_periodicities = (-6, -4, -3, -2, 1)
    if hrst_values is None:
        hrst_values = sorted({float(f"{x:.8g}") for x in np.logspace(-6, -1, num=30)})
    else:
        hrst_values = sorted({float(f"{x:.8g}") for x in hrst_values})

    scan_dir = _scan_root(cfg, d_tup)
    os.makedirs(scan_dir, exist_ok=True)
    method_dir = _method_dir(cfg, d_tup, m, MCS)
    os.makedirs(method_dir, exist_ok=True)
    method_subdir = _method_subdir(cfg, d_tup, m, MCS)

    ante_dir = _gaff2_old_ante_dir(cfg, d_tup, m)
    mol2_path = os.path.join(ante_dir, "MOL.mol2")
    frcmod_base_path = os.path.join(ante_dir, "MOL.frcmod")

    if not os.path.isfile(mol2_path):
        raise FileNotFoundError(f"Missing MOL.mol2 for {d_tup} at {mol2_path}")
    if not os.path.isfile(frcmod_base_path):
        raise FileNotFoundError(f"Missing base MOL.frcmod at {frcmod_base_path}")

    use_old_expanded = False
    frcmod_for_mdgx = frcmod_base_path

    if expand_basis:
        _top_exp, frcmod_exp = _ensure_expanded_inputs(
            cfg=cfg,
            log=log,
            method=m,
            d_tup=d_tup,
            basis_periodicities=tuple(int(x) for x in basis_periodicities),
        )
        use_old_expanded = True
        frcmod_for_mdgx = frcmod_exp
    else:
        log.info("[PARAM][%s][%s] expand_basis=False -> using original GAFF2/old frcmod", m, d_tup)

    _ensure_nc_from_xyz(cfg=cfg, log=log, method=m, d_tup=d_tup, MCS=MCS, use_old_expanded=use_old_expanded)

    atom_types = get_atom_types_from_mol2(mol2_path)
    results: Dict[float, Dict[str, str]] = {}

    for hrst_val in hrst_values:
        pfile, dat_path, out_path = param_input_file(
            atom_types=atom_types,
            method=m,
            dihedral_indices=d_tup,
            scan_dir=scan_dir,
            method_subdir=method_subdir,
            hrst_val=hrst_val,
            use_old_expanded=use_old_expanded,
        )

        subprocess.run(
            ["mdgx", "-i", os.path.basename(pfile)],
            cwd=os.path.dirname(pfile),
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        frcmod_dir = os.path.join(os.path.dirname(dat_path), "frcmod")
        os.makedirs(frcmod_dir, exist_ok=True)
        frcmod_path = os.path.join(frcmod_dir, f"{hrst_val}.frcmod")
        # When --multiplicity is used (expand_basis=True) the mdgx run already
        # uses the expanded frcmod with the requested basis periodicities.  For
        # the per-hrst output frcmod we start from the original GAFF2/old frcmod
        # (same multiplicities as parmchk2) and then *replace* the target-dihedral
        # block entirely with the newly fitted terms from the .dat, so no old
        # GAFF2 barrier values leak into GAFF2/new/hrst/antechamber/MOL.frcmod.
        frcmod_base_for_output = frcmod_base_path if expand_basis else frcmod_for_mdgx
        shutil.copy2(frcmod_base_for_output, frcmod_path)

        frcmod_path = update_frcmod(
            frcmod_path=frcmod_path,
            dat_path=dat_path,
            method=m,
            output_folder=frcmod_dir,
            replace_dat_keys=not expand_basis,
        )

        results[hrst_val] = {
            "input": pfile,
            "dat": dat_path,
            "out": out_path,
            "frcmod": frcmod_path,
        }

    if not results:
        raise RuntimeError(f"[PARAM][{m}][{d_tup}] all hrst runs failed")

    return results


def run_parametrization(
    log,
    cfg,
    method: str,
    d_tup: Tuple[int, int, int, int],
    MCS: bool = False,
    basis_periodicities: Optional[Tuple[int, ...]] = None,
    expand_basis: bool = True,
) -> Dict[float, Dict[str, str]]:
    log.info("[PARAM] start %s %s (MCS=%s expand_basis=%s)", method, d_tup, MCS, expand_basis)
    return parameterize_one_dihedral(
        cfg=cfg,
        log=log,
        m=method,
        d_tup=d_tup,
        MCS=MCS,
        basis_periodicities=basis_periodicities,
        expand_basis=expand_basis,
    )


# ============================================================================
# Cumulative frcmod bookkeeping
# ============================================================================

def update_cumulative_frcmod(
    cfg,
    final_frcmod: Dict[str, str],
    log,
    ROOT: str,
    m: str,
    d_tup: Tuple[int, int, int, int],
    dat_path: str,
    frcmod_base_path: str,
    tag: str = "",
    expand_basis: bool = True,
) -> None:
    dstr = _dstr(d_tup)
    key = m + (tag or "")

    final_dir = os.path.join(cfg.base_dir, "parameters")
    os.makedirs(final_dir, exist_ok=True)

    dihedral_frcmod = os.path.join(final_dir, f"{ROOT}_{m}{tag}_{dstr}.frcmod")
    shutil.copy2(frcmod_base_path, dihedral_frcmod)
    update_frcmod(dihedral_frcmod, dat_path, m, final_dir, replace_dat_keys=not expand_basis)

    cumulative_frcmod = final_frcmod.get(key)
    if cumulative_frcmod is None:
        cumulative_frcmod = os.path.join(final_dir, f"{ROOT}_{m}{tag}.frcmod")
        shutil.copy2(frcmod_base_path, cumulative_frcmod)
        final_frcmod[key] = cumulative_frcmod

    log.info("[FRCMOD%s][%s][%s] merge dat into cumulative: %s", tag, m, d_tup, cumulative_frcmod)
    update_frcmod(cumulative_frcmod, dat_path, m, final_dir, replace_dat_keys=not expand_basis)

    # Absorb any new_<m>.frcmod or new.frcmod produced by update_frcmod
    for candidate in (os.path.join(final_dir, f"new_{m}.frcmod"), os.path.join(final_dir, "new.frcmod")):
        if os.path.exists(candidate):
            os.replace(candidate, cumulative_frcmod)
            log.info("[FRCMOD%s][%s] updated cumulative using %s", tag, m, os.path.basename(candidate))
            break


def select_and_update_frcmod(
    log,
    cfg,
    ROOT: str,
    method: str,
    d_tup: Tuple[int, int, int, int],
    final_frcmod: Dict[str, str],
    param_results: Dict[float, Dict[str, str]],
    tag: str = "",
    MCS: bool = False,
    expand_basis: bool = True,
) -> str:
    nn_energy_file = _nn_energy_file(cfg, d_tup, method, MCS=MCS)
    if not os.path.exists(nn_energy_file):
        raise FileNotFoundError(
            f"[SELECT{tag}][{method}][{d_tup}] NN reference not found: {nn_energy_file}"
        )

    gaff2_new_dir = _gaff2_new_dir(cfg, d_tup, method)
    best_hrst, _best_frcmod_src, _best_rmse, best_profile_file = find_best_hrst_by_RMSE(
        nn_energy_file=nn_energy_file,
        gaff2_new_dir=gaff2_new_dir,
        log=log,
    )

    if best_hrst not in param_results:
        raise KeyError(
            f"Best hrst={best_hrst} not in param_results keys: {sorted(param_results.keys())}"
        )

    best_dat_path = param_results[best_hrst]["dat"]
    frcmod_base_path = os.path.join(_gaff2_old_ante_dir(cfg, d_tup, method), "MOL.frcmod")
    if not os.path.exists(frcmod_base_path):
        raise FileNotFoundError(f"Base MOL.frcmod not found at {frcmod_base_path}")

    update_cumulative_frcmod(
        cfg=cfg,
        final_frcmod=final_frcmod,
        log=log,
        ROOT=ROOT,
        m=method,
        d_tup=d_tup,
        dat_path=best_dat_path,
        frcmod_base_path=frcmod_base_path,
        tag=tag,
        expand_basis=expand_basis,
    )

    return best_profile_file
